#!/usr/bin/env python3
import boto3

with open("README.md", "w") as f:
    f.write("# boto3 client exceptions\n\n")
    f.write(
        "This is a generated list of all exceptions for each client within the boto3 library\n"
    )
    f.write("""
```python
import boto3

s3 = boto3.client("s3")
try:
  s3.create_bucket("example")
except s3.exceptions.BucketAlreadyOwnedByYou:
  raise
```\n\n""")
    services = boto3.session.Session().get_available_services()

    for service in services:
        f.write(f"- [{service}](#{service})\n")

    for service in services:
        f.write(f"### {service}\n")
        for _, value in boto3.client(
            service, region_name="us-east-1"
        ).exceptions.__dict__.items():
            for exception in value:
                f.write(f"- {exception}\n")
        f.write("\n")
