name: Boto3 Update

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U boto3
    - name: Generate exceptions
      run: |
        ./generate
    - name: Commit changes
      run: |
        if ! git diff-index --quiet HEAD --
        then
          boto3_version=$(pip3 show boto3 | grep Version | tr -d '[:space:]')
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -am "${boto3_version}"
          git push
        else
          echo "No changes to commit"
        fi
        exit 0
